export const MAPBOX_TOKEN = import.meta.env.VITE_MAPBOX_TOKEN || ''
export const DEFAULT_CENTER = [74.5698, 42.8746]
export const DEFAULT_ZOOM = 6.3
export const PLACE_SOURCE_ID = 'places-source'
export const PLACE_LAYER_ID = 'places-photo-layer'
export const PLACE_HIT_LAYER_ID = 'places-hit-layer'
export const PLACE_CLUSTER_LAYER_ID = 'places-cluster-layer'
export const PLACE_CLUSTER_MAX_ZOOM = 8
export const PLACE_PHOTO_MARKER_MIN_ZOOM = 8.2
